### PR TITLE
Added unlock user script

### PR DESCRIPTION
**Pull request by Barsonax**

### CODE REVIEW

**Comment by joostmeijles** [comment]
There actually exists a `unlock_admin.aspx` page in the default Sitecore installation. Does this script add value on top of that?

**Comment by Barsonax** [comment]
Yes that page does not work if the admin account is locked out because you cannot login.

**Comment by joostmeijles** [comment]
To make the page usable you set `enableUnlockButton = true`. Have you tried it?

**Comment by Barsonax** [comment]
The problem is that you have to login first to reach the page. This means you need a account that can login. In case all accounts are locked this is not possible.

**Pull request merged**
